
name: highrise-bot-egyptian
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - pip:
    - highrise-bot-sdk==24.1.0
    - aiohttp>=3.8.0
    - google-generativeai>=0.8.5
    - openai>=1.0.0
    - flask>=3.0.0
    - python-dotenv>=1.0.0
    - revchatgpt>=6.8.6
    - pychatgpt>=0.4.3.3
    - requests>=2.28.0
